### Create new patient Request

POST http://localhost:8282/api/v1/patients/save
Content-Type: application/json

{
  "name": "Sheldon Cooper",
  "email": "sheldon.cooper@caltech.edu",
  "address": "2311 North Los Robles Ave",
  "dateOfBirth": "1980-02-26",
  "registeredDate": "1999-09-15"
}
