### UPDATE patient request
PUT localhost:8282/api/v1/patients/update/98733785-ef2e-4ca1-82af-d582c0bd2785
Content-Type: application/json

{
  "name": "Sheldon Cooper updated",
  "email": "sheldon.cooper@caltech.edu",
  "address": "2311 North Los Robles Ave",
  "dateOfBirth": "1980-02-26"
}